defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: mspro
  password: mspro
  pool: 20
  timeout: 5

development:
  database: pro_dev
  <<: *defaults

production:
  database: pro_prod
  <<: *defaults

test: 
  database: pro_test
  <<: *defaults
